# Generated by Django 4.0.5 on 2022-07-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='geolocation',
        ),
    ]
